Code/Stacia/django_flask/blogproject/blogapp/urls.py

from django.urls import path 
from . import views

app_name = 'blogapp'
urlpatterns = [
   
    path('index', views.index, name = 'index'),
    path('create', views.create, name = 'create'),
    path('splash/', views.splash, name='splash'),
    path('home/',views.home, name="home"),
]

Code/Stacia/django_flask/blogproject/blogproject/urls.py
from user_system.views import register
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user_system/',include ('user_system.urls')),
    path ('blogapp/', include('blogapp.urls'))
    
]

Code/Stacia/django_flask/blogproject/user_system/urls.py
from django.urls import path 
from . import views

app_name = 'user_system'
urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/', views.login,name='login'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('create/', views.create, name='create'),
    path('base/', views.base, name='base'),
    # path('index', views.index, name = 'index'),
]

Code/Stacia/django_flask/blogproject/blogapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=100)
    rant = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title


Code/Stacia/django_flask/blogproject/user_system/models.py

from django.db import models
import datetime
from django.utils import timezone




    
    

Code/Stacia/django_flask/blogproject/blogapp/views.py
from django.shortcuts import render, reverse
from django.utils import timezone
import django.contrib.auth
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from .models import Post


def index(request):
    post = Post.objects.filter(public='True').order_by('-date_created')
    context = {
        'posts': posts,
    }
    return render(request, 'blog_app/index.html', context)

def splash(request):
    # print(request.POST)
    context ={
        'posts': Post.objects.all()
    }
    
    if request.method == 'POST':
        print(request.POST)
    # rant = request.POST['rant']
    return render(request, 'blogapp/splash.html', context)



def home (request):
    context ={
        'posts': Post.objects.all()
    }   
    
    return render(request, 'blogapp/home.html', context)


def create(request):
    # assign variables
    title = request.POST['title']
    rant = request.POST['rant']
   
    
    # assigning the user
    user = django.contrib.auth.get_user(request)
    post = Post(title=title, rant=rant,  author=user)
    post.save()\

    print(post)
    return HttpResponseRedirect(reverse('blogapp:splash'))

Code/Stacia/django_flask/blogproject/user_system/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
import django.contrib.auth
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages

# Create your views here.

def register(request):
    print(request.POST)
    # get post and asign dictionary keys from form.
    if request.method == 'POST':
        # if form.is_valid(): 
        # form = User(request.POST)
        username = request.POST['username']
        email = request.POST ['email']
        password = request.POST['password']
        existing_user = User.objects.filter(username=username).first()

        # check if user exists
        if existing_user is not None:
            return render(request, 'user_system/register.html', {'error': 'That username is already taken'})
        user = User.objects.create_user(username, email, password)
        django.contrib.auth.login(request, user)
         
        # form.save()
        return HttpResponseRedirect(reverse('blogapp:splash'))
    return render(request, 'user_system/register.html')


def base(request):
    return render(request, "user_system/base.html")
    
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = django.contrib.auth.authenticate(request, username=username, password=password)
        if user is not None:
            django.contrib.auth.login(request, user)
            messages.success(request, f" hi {username}!")
            return HttpResponseRedirect(reverse('blogapp:splash'))
        else:
            return render(request, 'user_system/login.html', {'error': 'Bad news, thats not your user name, Good NEWS! That username is avalible!'})
    return render(request, 'user_system/login.html')
     
@login_required
def profile(request):
    print(request.user.username)
    return render(request, 'user_system/profile.html')

def logout(request):
    django.contrib.auth.logout(request)
    return HttpResponseRedirect(reverse('user_system:login'))



def create(request):
    # check that we received form data
    print(request.POST)
    # get the values out of the form data
    
      # create a record and save it to the database
    user = User(user_name=user_name, password=password,)
    user.save()
    return HttpResponse ("home")



Code/Stacia/django_flask/blogproject/user_system/templates/user_system/base.html
{% load static %}
<html>

<head>
  <title>{% block title %}Welcome {{user.username}}{% endblock %}</title>

  <style>
:root{

--basepanel: #2f2f4f;
--bevelshaddow: #191970;
--bevelhighlight: #d01ee0;


--baselight: #3cb371;
--lightwarm: #7cfc00;
--lightreflect: #7fffd4;
--otherpink: #d4568b;
--button:#b8869b;
--chillerblue:#a4cadb;
}

body{
  padding:5%;
  padding-right:5% ;
display:flex;
margin:0px;
flex-direction: column;
background-color: var(--basepanel);
}

.basepannel{
display: grid;
 background-color: var(--basepanel); 

 height:100%;
padding:15%;

font-family: 'Orbitron', sans-serif;


/* width:auto;
min-width:100%; */

grid-template-columns: 10% 20%  auto  15% 10% ;
grid-template-rows: 15% auto  15%;
grid-template-areas:
". . . header ."

"s s1 main s2 . "
"f f f f f"

;
}

.fancytext{
  height:100px;
  color: #fff;
  text-shadow:
  0 0 7px #fff,
  0 0 10px #fff,
  0 0 21px #fff,
  0 0 42px #0fa,
  0 0 82px #0fa,
  0 0 92px #0fa,
  0 0 102px #0fa,
  0 0 151px #0fa;
  display:flex;
  width:60%;
  justify-content: center;
  align-content: center;
  border: 3px solid rgb(216, 19, 150);
  border-radius: 25% 10%;
  box-shadow: 10px 10px 5px var(--lightreflect);
  font-family: 'Audiowide', cursive;
}

header{
grid-area: header;
height:100px;
color: #fff;
text-shadow:
  0 0 7px #fff,
  0 0 10px #fff,
  0 0 21px #fff,
  0 0 42px #0fa,
  0 0 82px #0fa,
  0 0 92px #0fa,
  0 0 102px #0fa,
  0 0 151px #0fa;
  display:flex;
  width: grow 1;
  justify-content: center;
  align-content: center;
  border: 3px solid rgb(216, 19, 150);
  border-radius: 25% 10%;
  box-shadow: 10px 10px 5px var(--lightreflect);
  font-family: 'Audiowide', cursive;
}

.footer{
  grid-area: foot;
  display :grid;
  justify-content: space-around;
  align-content: space-around;
  flex-direction: row;
  background-color: var(--basepanel);
  width:100%
}
.display {
  display: flex;
  grid-area: main;
  
  width:80%;
  flex-direction: column;
  margin-top: 10%;
  border: solid rgb(216, 19, 150);
  border-radius: 25% 10%;
  box-shadow: 10px 10px 5px var(--bevelshaddow);
  background-color: var(--button);
  padding:5%;
 
}
.secrets
.box{
  display:flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 10px;
}
.pinkring{
  border: solid 2px rgb(216, 19, 150);
  border-radius: 25% 10%;
  box-shadow: 10px 10px 5px var(--bevelshaddow);
  padding:20px;
  margin-bottom: 5%;
  display:flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
}
.box{
  display:flex;
  width:auto;
  flex-grow: 1;
  margin-top: 10%;
}
.title{
  
  display:flex;
  align-items:center;
  justify-content: center;
  margin-bottom: 5%;
  background-color: var(--basepanel);
  box-shadow: 10px 10px 10px 10px var(--bevelshaddow);
  width:75%;
  border-radius: 25% 10%;
}
.col{
  display:flex;
  flex-direction: column;
  height:100%;
  margin-bottom: 2%;
}

.panel{
  display:flex;
  flex-direction: column;
  background-color: var (--otherpink);
  width:100%;
  height:100%;
}
</style>
</head>

<body>
  {% block head %}
  <header>
    <div>
      <h1>Secret Club</h1>
      <div class = "col">
        {% if user.is_authenticated %}
        
        <div>Welcome {{user.username}}</div>
        <div><a href="{% url 'user_system:logout' %}">Logout</a></div>
        {% else %}
        <div><a href="{% url 'user_system:login' %}">Login</a></div>
        <div><a href="{% url 'user_system:register' %}">Register</a></div>
        {% endif %}
      </div>
    </div>
    
  </header>
  {% endblock %}
  {% block float %}
  
  {% endblock %}
  <main>
    {% if messages %}
    {% for message in messages %}
    <div>
      {{message}}
    </div>
    {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock %}
  </main>
  <footer>
    {% block foot %}
    <div class="bottombar">
      <h1>secret club</h1>
      <span>&copy; Stacia Class Eagle PDX Code Guild 2020</span>
    </div>
  </footer>
  {% endblock %}

</body>

</html>

Code/Stacia/django_flask/blogproject/user_system/templates/user_system/index.html
{% extends 'user_system/base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<p>this is the page content for the index page</p>
{% endblock %}

Code/Stacia/django_flask/blogproject/user_system/templates/user_system/login.html
{% extends 'user_system/base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>





    <div class="basepannel">
        

        <!-- <div class="panel"> -->

            <div class="display">
            <form action="{% url 'user_system:login'%}" method="POST" id="Login-Form">
                {% csrf_token %}

                    <div>
                        <h1> Get in there!</h1>
                    </div>
                    <div class='box'>

                        <label for="username">User Name </label>
                        <input id="username" name="username" type="text">
                    </div>
                    <div class="box">
                        <label for="password">Password </label>
                        <input id="password" name="password" type="text">
                    </div>
                    <button input type="submit" class="btn">Submit</button>
            </form>
        <!-- </div> -->
    </div>
    <div class="footer">
        <div class="panel"> Wanna get in on this? <a href="{%url 'user_system:register'%}">Register here!</a> </div>
</div>


</html>
{% endblock %}
{%block foot%}
{% endblock %}

Code/Stacia/django_flask/blogproject/user_system/templates/user_system/profile.html

{% extends 'user_system/base.html' %}
{% block content %} 

    
    <div class='container'>
        <div class = "topbar">
            <h1> Yeah</h1>
        </div>
        <div class= "floatbox"><p>This is a text this is a text about nothing. This text exists for the simple moment of existing and nothing more. It exists to hold space. To be, and to exist. It shall occupy the space in which it exists in this form and many other forms. It shall be a holder of space while it is needed. It shall sow space beyond the space it is allotted as it exists now until it is needed next. This text holds a moment of interaction and awareness of existing, of the realness in the moment and meta existentiality and the human moment of awareness, declaration, and acknowledgement of belief and value of the validity of existence for joy. </p></div>
        <div class ='column'>
            <form.as_p action="" method="POST" id="User">
                {% csrf_token %}
                <div class= "bar">
                    
                    <div class="title"> <h1> Login</h1></div>
                    <div class='box'>
                        
                        <label for ="user_name">User Name</label>
                        <input id="user_name" name="user_name" type="text">
                    </div>
                    <div class="box">
                        <label for ="password">Password   </label>
                        <input id="password" name="password" type="text">
                    </div>
                    <div class ="box">
                        <label for ="email">Email</label>
                        <input id ="email" name ="email" type = "email">
                    </div>
                    <div class="box">
                        
                        <button input type="submit" class="btn">Login </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class ="bottombar">
        <h1>secret club</h1>
    </div>
    <div> need an Account? <a href ="{%url 'user_system:register'%}"> register here!</a> </div>
        

{% endblock %}

Code/Stacia/django_flask/blogproject/user_system/templates/user_system/register.html
{% extends 'user_system/base.html' %}
{% block content %}
<div class="pinkring">
    <div class="col">
        <div class="pinkring">


            <div class='display'>
                <div class="pinkring">
                    <h1> Yeah</h1>
                    <div class="pinkring">
                        <p>This is a text this is a text about nothing. This text exists for the simple moment of
                            existing
                            and
                            nothing more. It exists to hold space. To be, and to exist. It shall occupy the space in
                            which
                            it
                            exists in this form and many other forms. It shall be a holder of space while it is needed.
                            It
                            shall
                            sow space beyond the space it is allotted as it exists now until it is needed next. This
                            text
                            holds
                            a moment of interaction and awareness of existing, of the realness in the moment and meta
                            existentiality and the human moment of awareness, declaration, and acknowledgement of belief
                            and
                            value of the validity of existence for joy. </p>
                    </div>
                </div>
                <div class='pinkring'>
                    <form action="{% url 'user_system:register'%}" method="POST" id="User">
                        {% csrf_token %}
                        <div class="col"></div>

                        <div class="title">
                            <h1> Assimilate</h1>
                        </div>
                        <div class='box'>

                            <label for="username">User Name</label>
                            <input id="username" name="username" type="text">
                        </div>
                        <div class="box">
                            <label for="password">Password </label>
                            <input id="password" name="password" type="text">
                        </div>
                        <div class="box">
                            <label for="email">Email</label>
                            <input id="email" name="email" type="email">
                        </div>
                        <div class="box">

                            <button input type="submit" class="btn">Submit</button>
                        </div>
                </div>
                </form>
            </div>
        </div>
        <div class="fancytext"> Already Crew?   <a href="{%url 'user_system:login'%}">        login here!</a> </div>
    </div>
</div>




{% endblock %}