Code/Mark/3 Django/Lab02_ToDo/todo_proj/todo_app/urls.py
from django.urls import path
from . import views

app_name = 'todo_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:todoitem_id>/delete/', views.delete, name='delete')
]

Code/Mark/3 Django/Lab02_ToDo/todo_proj/todo_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo_app', include('todo_app.urls'))
]

Code/Mark/3 Django/Lab02_ToDo/todo_proj/todo_app/models.py
from django.db import models

class Priority(models.Model):
    name = models.CharField(max_length=15)
    def __str__(self):

        return self.name


class TodoItem(models.Model):
    title = models.CharField(max_length=100)
    priority = models.ForeignKey(Priority, on_delete=models.PROTECT)
    detail = models.CharField(max_length=200, null=True, blank=True)
    created_date = models.DateField()
    due_date = models.DateField(blank=True, null=True)
    due_time = models.CharField(max_length=10, null=True)
    def __str__(self):

        return self.title


class Archive(models.Model):
    title = models.CharField(max_length=100)
    detail = models.CharField(max_length=200)
    due_date = models.DateField()
    completed_date = models.DateField()
    def __str__(self):
        return self.title

Code/Mark/3 Django/Lab02_ToDo/todo_proj/todo_app/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import TodoItem, Priority, Archive
from datetime import datetime
from django.utils import timezone
import requests









def index(request):
    # added an api for some inspirational quotes
    url = 'https://inspiration.goprogram.co.uk'
    response = requests.get(url)
    data = response.json()
    quote = data['quote']
    author = data['author']
    todo_items = TodoItem.objects.order_by('-priority')
    archives = Archive.objects.order_by('completed_date')
    priorities = Priority.objects.all()
    context = {
        'title': 'Todo List',
        'todo_items': todo_items,
        'priorities' : priorities,
        'quote': quote,
        'author': author,
        'archives': archives
    }
    
    return render(request, 'todo_app/index.html', context)


def create(request):
    print(request.POST)
    # saving the data recieved to variables
    title = request.POST['title']
    priority = request.POST['priority_id']
    due_date = request.POST['due_date']
    detail = request.POST['detail']
    due_time = request.POST['due_time']
    due_date = datetime.strptime(due_date, '%b %d, %Y') # using strptime to get the date in the format needed
    created_date = timezone.now()
    # sending and saving the information to the database
    todoitem_set = TodoItem(title=title, priority_id=priority, due_date=due_date, due_time=due_time, created_date=created_date, detail=detail)
    todoitem_set.save()
    # trying out the reverse lookup  option
    return HttpResponseRedirect(reverse('todo_app:index'))

# on delete items will be added to the archive and removed from the todo list
def delete(request, todoitem_id):
    todoitem_set = TodoItem.objects.get(id=todoitem_id)
    title = todoitem_set.title
    detail = todoitem_set.detail
    due_date = todoitem_set.due_date
    completed_date = timezone.now()
    archive_set = Archive(title=title, detail=detail, due_date=due_date, completed_date=completed_date)
    archive_set.save()
    todoitem_set.delete()
    return HttpResponseRedirect(reverse('todo_app:index'))

Code/Mark/3 Django/Lab02_ToDo/todo_proj/todo_app/templates/todo_app/index.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{title}}</title>
    <!-- Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Materialize CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet"  href="https://fonts.googleapis.com/css?family=Mate+SC">
    <style>
        body {
            background-image: url("{% static 'todo_app/background3.jfif' %}");
            background-position: center;
            background-repeat: no-repeat;
            font-family: 'Mate SC';
            background-attachment: fixed;
        }

        .Low {
            background-color: lightblue;
        }

        .Medium {
            background-color: yellow;
        }

        .High {
            background-color: rgb(223, 50, 37);
        }

        #form {
            border-style: solid;
            margin: 5px;
            padding: 5px;
            background-color: white;
        }
        nav {
            background-color: rgba(2, 2, 2, 0.5);
        }
        #quote {
            background-color: rgba(21,2,89,0.75);
            border-style: solid;
            border-color: rgb(130,104,166);
            margin-top: .25in;
        }
        #title_bar {
            display: flex;
            justify-content: space-between;
        }
        #footer {
            background-color: rgba(2, 2, 2, 0.5);
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            margin-top: .25in;
            padding-left: .25in;
            height: 50px;
            display: flex;
            align-items: center;
        }
        #due_date {
            display: flex;
            flex-direction: row;
            justify-content: center;
        }
    </style>
</head>

<body>
    <nav>
        <div class="nav-wrapper">
            <a href="#" class="brand-logo center">{{title}}</a>
        </div>
    </nav>


    <div id="quote" class="container center-align white-text">
        <h6>Quote of the moment:</h6>
        <h5>"{{ quote }}"</h5>
        <p>-{{ author }}</p>
    </div>
    <!-- Displaying current items on the todo list -->
    <div class="container">
        <div class="col">
            <ul class="collapsible">
                {% for todo_item in todo_items %}
                <li>
                    <div id="title_bar" class="collapsible-header {{ todo_item.priority }}">
                        <h6 id="todo_title">Task: {{ todo_item.title}}</h6>
                        <a class="btn red" href="{% url 'todo_app:delete' todo_item.id %}">Completed</a>
                    </div>
                    <div class="collapsible-body deep-purple lighten-2">
                        <ul>
                            <li>Priority: {{ todo_item.priority }}</li>
                            <li>Due Date: {{ todo_item.due_date }} @ {{todo_item.due_time}}</li>
                            <hr>
                            <li>Detail: {{ todo_item.detail }}</li>
                        </ul>
                    </div>
                </li>
                {% endfor %}
            </ul>

        </div>
        <!-- Form submission to add items to the todo list -->
        <div class="col">
            <form action="{% url 'todo_app:create' %}" id="form" class=" z-depth-4" method="POST">
                {% csrf_token %}
                <!-- Title -->
                <div class="input-field col s12">
                    <input id="title" type="text" class="validate" name="title" placeholder="Task" required>
                </div>

                <!-- Priority -->
                <div class="input-field col s12">
                    <select name="priority_id" required>
                        {%for priority in priorities%}
                        <option value="{{priority.id}}">{{priority}}</option>
                        {%endfor%}
                    </select>
                    <label>Priority</label>
                </div>
                <!-- Details -->
                <textarea id="textarea1" class="materialize-textarea" name="detail" placeholder="Additional Information"></textarea>
                <!-- Due date -->
                <div id="due_date">
                    <span><input type="text" id="due_date" class="datepicker" name="due_date" required></span>
                    <label for="due_date">Due Date</label>
                    <span><input type="text" name="due_time" class="timepicker" required></span>
                </div>

                <div id="due_date">
                    <button id="submit" type="submit" class="btn orange">Submit</button>
                </div>
            </form>
        </div>
    </div>
    <!-- An archive list of already completed items -->
    <div id="quote" class="container white-text">
        <table class="responsive-table">
            <thead>
              <tr>
                  <th>Title</th>
                  <th>Detail</th>
                  <th>Due Date</th>
                  <th>Completed Date</th>
              </tr>
            </thead>
            {% for archive in archives%}
            <tbody>
              <tr>
                <td>{{ archive.title }}</td>
                <td>{{ archive.detail }}</td>
                <td>{{ archive.due_date }}</td>
                <td>{{ archive.completed_date }}</td>
              </tr>
            </tbody>
            {%endfor%}
          </table>        
    </div>



    

    <footer id="footer" class="white-text">
        &copy; Class Eagle 2021
    </footer>




    <!-- Materialize JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('select');
            var instances = M.FormSelect.init(elems, {});
        });

        document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('.datepicker');
            var instances = M.Datepicker.init(elems, {});
        });

        document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('.collapsible');
            var instances = M.Collapsible.init(elems, {});
        });

        document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelectorAll('.timepicker');
            var instances = M.Timepicker.init(elems, {});
        });

    </script>
</body>

</html>