Code/Stacia/django_flask/Todoproj/Todoproj/urls.py

from django.urls import path, include
from django.contrib import admin
app_name = 'todoapp'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls')),
]


Code/Stacia/django_flask/Todoproj/todoapp/urls.py
from django.urls import path 
from . import views

app_name = "todoapp"
urlpatterns = [
     path('', views.index, name='index'),
     path('create/',views.create, name="create"),
     path('done/<int:todo_id>',views.done, name="done")
]

Code/Stacia/django_flask/Todoproj/todoapp/models.py
from django.db import models
import datetime
from django.utils import timezone




class Todo(models.Model):
    name = models.CharField(max_length=200)
    priority = models.CharField(max_length=200, default="Low")
    deadline = models.DateField(auto_now_add=True)
    ogday = datetime.date.today()
    done = models.BooleanField()
    

    def __str__(self):
        return self.name

Code/Stacia/django_flask/Todoproj/todoapp/forms.py
class ChecklistForm(forms.ModelForm):

    class Meta:
        model = Todo
        fields= ("done")

    def save(self, todo=None):
        todo = super(ChecklistForm, self).save(commit=False)

        if name:
            Todo.name = name
        todo.save()
        return todo

Code/Stacia/django_flask/Todoproj/todoapp/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.db import models
from datetime import datetime
from .models import Todo






        
def index(request):
    todos = Todo.objects.all()
    

    context = {
        
        "todos":todos,
    }
    return render(request, 'todoapp/index.html', context)


def create(request):

    # if request.method =='POST':
    # check that we received form data
    # print(request.POST)
    print(request.POST)
    # get the values out of the form data

    name = request.POST.get('todo')
    priority= request.POST.get('priority')
    
    
    done= False

        # # create a record and save it to the database
    todo = Todo.objects.create(name=name, priority=priority,done = done)
    todo.save()

    # redirect to the index page
    
    return HttpResponseRedirect(reverse('todoapp:index'))

def done(request, todo_id):
    print(request.POST)
    # # print(todo_element)
    # # get the values out of the form data
    todo = Todo.objects.get(id=todo_id)
    # task = request.POST['todo']
    # console.log(task)
    # print(task.name)
    # priority_string = request.POST['priority']
    # priority = Priority.objects.get(name=priority_string)
    todo.done =True
    # todo = todo()
    # todo.name= name 
    # todo.priority = priority
    # todo.save = true
    todo.save()
    # print (todo)
    
    # create a record and save it to the database
    # done_todo = Done(task=task, priority=priority,created=created)
    # done_todo.save()
    # todo_element.delete()
    # redirect to the index page
 
    return HttpResponseRedirect(reverse('todoapp:index'))



Code/Stacia/django_flask/Todoproj/todoapp/templates/todoapp/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">
  <style>
    body {
      height: 100%;
      width: 100%
    }

    .textbox {
      width: 200px;
      height: 500px;
      background-color: blanchedalmond;
    }

    .title {

      background-color: aquamarine;
      font-size: 32px;
      text-align: center;
      font-family: 'Indie Flower', cursive;
      padding-top: 20px;
    }


    .sidebar {
      background-color: bisque;
    }

    .menu {
      visibility: hidden;
    }

    button+.menu:active,
    button:focus+.menu {
      visibility: visible;
    }

    .left {
      border: 3px solid darkseagreen;
      border-radius: 60px;
      background-color: honeydew;
      padding-left: 10px;
      padding-right: 10px;
      padding-top: 20px;
      padding-bottom: 20px;
    }

    .center {
      border: 3px solid darkseagreen;
      border-radius: 60px;
      background-color: honeydew;
      padding-left: 10px;
      padding-right: 10px;
      padding-top: 20px;
      padding-bottom: 20px;

    }

    .right {
      border: 3px solid darkseagreen;
      border-radius: 60px;
      background-color: honeydew;
      padding-left: 10px;
      padding-right: 10px;
      padding-top: 20px;
      padding-bottom: 20px;
    }

    .form {
      display: grid;
      flex-direction: column;
      height: 800px;
      justify-content: space-between;
    }

    .list {
      background-color: rgb(199, 199, 238);
      height: 100px;
      width: 100px;
      display: flex;
      flex-direction: column;
    }

    .blacktext {
      color: black;
    }

    .container {
      display: flex;
      align-items: stretch;
      /* align-content: center; */
      justify-content: space-around;
      width: 100%;
      background-color: burlywood;
      height: 100%;

    }

    .box {

      background-color: beige;
      height: 200px;
      border-radius: 60px;
      border: 3px solid blueviolet;


      padding-left: 50px;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
    }

    .notepad {
      background-color: rgb(33, 36, 211);

      display: flex;
      flex-direction: column;

      justify-content: space-around;
      /* width: 40%; */


    }

    .dummy {}

    .logbook {
      border: 3px solid blueviolet;
      background-color: darksalmon;
      display: flex;
      flex-direction: row;
      justify-content: space-around;

    }

    .todos {
      flex-grow: 1;
      display: flex;
      flex-direction: column;

    }

    .todos>div {
      /* flex-grow:1; */

    }

    .done {
      width: 100%;
      color: aliceblue;

    }
  </style>
</head>

<body>

  <div class="container">




    <div class="notepad">
      <div class="title">
        <span> Get shit done</span>
      </div>


      <form action="{% url 'todoapp:create' %}" method="post" id="todo">
        {% csrf_token %}


        <div class="box">
          <label for="todo">Task</label>
          <input id="todo" name="todo" type="text">
        </div>

        <div class="box">

          <label for="priority">How urgent is this task?:</label>
          <select id="priority" name="priority" size="4" multiple>
            <option value="Urgent">Urgent</option>
            <option value="Important">Important</option>
            <option value="Medium">Medium</option>
            <option value="Low">Low</option>
          </select>

        </div>


        <!-- click to print  -->
        <div class="box">
          <button input type="datetime-local" id="submit" name="time" value="time" class="btn">Submit</button>
        </div>

      </form>

    </div>

    <div class="todos">
      <div class="title">Things to do.</div>


      {%for todo in todos%}


      {%if todo.done != True%}
      <div class="logbook">

        <div class="left">

          <p >{{todo.name}}</p>
        </div>

        <div class="center">
          <p >{{todo.priority}}</p>
        </div>



        <form action="{% url 'todoapp:done' todo.id %}" method="post" id="todo">
          {% csrf_token %}

          <button id="submit" name="done" value="done">DONE!</button>
        </form>
      </div>
      {%endif%}
      {%endfor%}

    </div>
  </div>
  </div>
  <div class="done">
    <div class="title">done</div>
    {%for todo in todos%}


    <div class="logbook"></div>

    {%if todo.done == True%}



    <p class ="blacktext">{{todo.name}}</p>



    <p class ="blacktext">{{todo.priority}}</p>

    {%endif%}
    {%endfor%}
  </div>

</body>

</html>