Code/Russell/4 JavaScript/Pokedex_proj/Pokedex_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('poke_app/', include('poke_app.urls'))
]

Code/Russell/4 JavaScript/Pokedex_proj/poke_app/urls.py
from django.urls import path
from . import views

app_name = 'poke_app'
urlpatterns = [
    path ('index/', views.index, name='index'),
    path ('pokemon/', views.pokemon, name='pokemon')
]

Code/Russell/4 JavaScript/Pokedex_proj/poke_app/models.py
from django.db import models

class PokemonInfo(models.Model):
    number = models.IntegerField()
    name = models.CharField(max_length=200)
    height = models.FloatField()
    weight = models.FloatField()
    image_front = models.CharField(max_length=200)
    image_back = models.CharField(max_length=200)
    types = models.CharField(max_length=200)

def __str__(self):
    return self.name

Code/Russell/4 JavaScript/Pokedex_proj/poke_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from .models import PokemonInfo


def index(request):
    return render(request, 'poke_app/index.html')


def pokemon(request):

    pokemon = PokemonInfo.objects.all()
    pokemon_data = []
    for pokemons in pokemon:
        pokemon_data.append({
            'number': pokemons.number,
            'name': pokemons.name,
            'height': pokemons.height,
            'weight': pokemons.weight,
            'image_front': pokemons.image_front,
            'image_back': pokemons.image_back,
            'types': pokemons.types

        })
    return JsonResponse({'pokemon':pokemon_data})
   
    # return HttpResponse('yo')

Code/Russell/4 JavaScript/Pokedex_proj/poke_app/templates/poke_app/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello World!</title>
    <!-- Materialize CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
</head>

<body>
    <!-- Page Content -->
    <div id="app">
        <h1>[[ Pokemon ]]</h1>
        <!-- this is where I left off and I'm getting an error in the browser-->
        <tr v-for= "pokemons in pokeInfo">
            <td>[[pokemon.name]]</td>
            <td></td>
            <td></td>
        </tr>
        


    </div>
    <!-- Materialize JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <!-- Vue JS -->
    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script type="text/javascript">
        // initialize Materialize components
        M.AutoInit()

        let app = new Vue({
            el: '#app',
            delimiters: ["[[", "]]"],
            data: {
                title: 'Let\s tag it and bag it!'
            },

            methods: {
                getPokemon: function() {
                    axios({
                        method: 'get',
                        url: '{% url "poke_app:pokemon" %}',
                       
                    }).then(response => {
                        console.log(response.data)
                        
                    })
                },
            },

            created: function(){
                this.getPokemon()
            }
        })
    </script>
</body>

</html>